DOMAIN = "mipower"
PLATFORMS = ["switch"]

# options / defaults
CONF_BACKEND = "backend"
BACKEND_BLUETOOTHCTL = "bluetoothctl"
BACKEND_BLEAK = "bleak"
DEFAULT_BACKEND = BACKEND_BLUETOOTHCTL

DEFAULT_TIMEOUT_SEC = 8
DEFAULT_RETRY_COUNT = 2
DEFAULT_RETRY_DELAY_SEC = 2
