wake:
  description: "Wake (connect) the device."
  fields:
    entity_id:
      description: "Entity_id of the mipower switch"
      example: "switch.mipower_e0_b6_..."
sleep:
  description: "Put device to sleep (disconnect)."
  fields:
    entity_id:
      description: "Entity_id of the mipower switch"
      example: "switch.mipower_e0_b6_..."
